# Generated by Django 3.1.7 on 2021-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Посетитель', 'verbose_name_plural': 'Посетители'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заселение', 'verbose_name_plural': 'Заселения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Класс номера', 'verbose_name_plural': 'Классы номеров'},
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Свободен', 'Свободен'), ('Занят', 'Занят')], max_length=20, verbose_name='Статус номера'),
        ),
    ]
