# Generated by Django 3.1.7 on 2021-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210314_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='foreigner',
        ),
        migrations.AddField(
            model_name='client',
            name='stay',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('М', 'male'), ('Ж', 'female')], max_length=20, verbose_name='Пол'),
        ),
    ]
