# Generated by Django 3.1.7 on 2021-03-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210314_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='stay',
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Ж', 'female'), ('М', 'male')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Свободен', 'Свободен')], max_length=20, verbose_name='Статус номера'),
        ),
    ]
