# Generated by Django 3.1.7 on 2021-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20210317_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Свободен', 'Свободен')], default='Свободен', max_length=20, verbose_name='Статус номера'),
        ),
    ]
