# Generated by Django 3.1.7 on 2021-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20210318_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=20, verbose_name='Пол'),
        ),
    ]
