# Generated by Django 3.1.7 on 2021-03-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20210318_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='desc',
            field=models.TextField(verbose_name='Описание номера'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='rooms_qty',
            field=models.IntegerField(verbose_name='Количество комнат в номере'),
        ),
    ]
