# Generated by Django 3.1.7 on 2021-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20210318_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Свободен', 'Свободен'), ('Занят', 'Занят')], default='Свободен', max_length=20, verbose_name='Статус номера'),
        ),
    ]
