# Generated by Django 3.1.7 on 2021-04-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20210320_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='rooms_qty',
        ),
    ]
