# Generated by Django 3.1.7 on 2021-04-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_roomcategory_rooms_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='free_rooms',
            field=models.IntegerField(default=0, verbose_name='Свободные номера'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Свободен', 'Свободен')], default='Свободен', max_length=20, verbose_name='Статус номера'),
        ),
    ]
