# Generated by Django 3.1.7 on 2021-04-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20210401_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='persons',
            field=models.IntegerField(default=1, verbose_name='Количество гостей'),
        ),
    ]
