# Generated by Django 3.1.7 on 2021-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_auto_20210404_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Заселено', 'Заселено'), ('Новый', 'Новый'), ('Подтвержден', 'Подтвержден')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женщина'), ('М', 'Мужчина')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Занят', 'Занят'), ('Свободен', 'Свободен')], default='Свободен', max_length=20, verbose_name='Статус номера'),
        ),
    ]
