# Generated by Django 3.1.7 on 2021-04-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20210404_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Заселено', 'Заселено'), ('Подтверждено', 'Подтверждено'), ('Новый', 'Новый')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Свободен', 'Свободен'), ('Занят', 'Занят')], default='Свободен', max_length=20, verbose_name='Статус номера'),
        ),
    ]
