# Generated by Django 3.1.7 on 2021-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_auto_20210404_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Подтвержден', 'Подтвержден'), ('Заселено', 'Заселено')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
