# Generated by Django 3.1.7 on 2021-04-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0023_auto_20210407_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=75, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=75, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport',
            field=models.BigIntegerField(default=0, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(max_length=75, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Заселено', 'Заселено'), ('Подтвержден', 'Подтвержден'), ('Новый', 'Новый')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женщина'), ('М', 'Мужчина')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
