# Generated by Django 3.1.7 on 2021-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_auto_20210413_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Заселено', 'Заселено'), ('Новый', 'Новый'), ('Подтвержден', 'Подтвержден')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=20, verbose_name='Пол'),
        ),
    ]
