# Generated by Django 3.1.7 on 2021-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_auto_20210413_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Заселено', 'Заселено'), ('Подтвержден', 'Подтвержден')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
