# Generated by Django 3.1.7 on 2021-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_auto_20210413_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('Can delete Бронь', 'Может водить'), ('Can view Бронь', 'Может водить'))},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Подтвержден', 'Подтвержден'), ('Новый', 'Новый'), ('Заселено', 'Заселено')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
